### ISSUE TITLE
SqlPersistT MonadThrow, MonadCatch, MonadMask instances?

### ISSUE THREAD

**Issue by ikv** [brandonchinn178/persistent-mtl#36]

**Comment by brandonchinn178** [comment]
Do you mean SqlQueryT? Yes, we can add those instances. The instances shouldnt be added for SqlTransaction, though, because of the retry logic in it.

PR welcome!

**Comment by ikv** [comment]
>  The instances shouldnt be added for SqlTransaction, though, because of the retry logic in it.

Can you please elaborate?

**Comment by brandonchinn178** [comment]
So the whole point of SqlTransaction is that it contains actions running within a single transaction. But some databases (e.g. postgres) require you to retry transactions if it fails, which is why you can specify retry logic in runSqlQueryTWith.

So imagine if you run
```hs
withTransaction $ m1 `finally` m2
```
and postgres throws an error in m1 that tells you you need to rerun the transaction. In this code block, m2 would try to run (and throw the error again if it does any db actions). If m2 is a noop like `return ()` then it would swallow the retry error and prevent the retry logic from happening.

I'm pretty sure there are other Bad Things that can happen too. But do you actually need MonadCatch/MonadMask on SqlTransaction? If you add the instances to SqlQueryT, it should handle most use cases; it just wouldnt support running MonadCatch code in withTransaction
